# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Cocoapods"
  lane :dependencies do
    cocoapods
  end

  desc "Build"
  lane :build do
    build_ios_app(
      scheme: "TodoApp",
      export_method: "development"
    )
  end

  desc "Tests"
  lane :test do
    run_tests(
      scheme: "TodoApp",
      output_types: "junit",
      output_directory: "build",
      output_files: "test_result.xml"    
    )
  end

  desc "Report Linters from Pods"
  lane :lint do
    swiftlint(
        executable: "Pods/SwiftLint/swiftlint",
        output_file: "build/swiftlint.html",
        ignore_exit_status: true,
        reporter: "html"
    )    
  end

  desc "Slather"
  lane :codecoverage do
    slather(
      use_bundle_exec: "true",
    )
  end

  desc "CI"
  lane :ci do
    dependencies
    test
    codecoverage
    lint
  end
end
