# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Cocoapods"
  lane :dependencies do
    cocoapods
  end

  desc "Build"
  lane :build do
    build_ios_app(
      scheme: "TodoApp",
      export_method: "development"
    )
  end

  desc "Tests"
  lane :test do
    run_tests(
      scheme: "TodoApp",
      output_types: "junit",
      output_directory: "build",
      output_files: "test_result.xml"    
    )
  end

  desc "Report Linters from Pods"
  lane :lint do
    swiftlint(
        executable: "Pods/SwiftLint/swiftlint",
        output_file: "build/swiftlint.html",
        ignore_exit_status: true,
        reporter: "html"
    )    
  end

  desc "Slather"
  lane :codecoverage do
    slather(
      use_bundle_exec: "true",
    )
  end

  desc "CI"
  lane :ci do
    dependencies
    test
    codecoverage
    lint
  end

  desc "Fetch provisioning and certificates"
  lane :fetch_signings do
    match(
      type: "appstore",
      clone_branch_directly: true,
      readonly: true
    )
  end

  desc "Archive"
  lane :archive do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "TodoApp.xcodeproj",
    )

    update_project_team(
      path: "TodoApp.xcodeproj",
      teamid: "4965NT4QX9"
    )

    build_ios_app(
      scheme: "TodoApp",
      export_method: "app-store",
      build_path: "build/archive/build",
      archive_path: "build/archive/archive",
      output_directory: "build/",
      output_name: "app.ipa",
      export_options: {
        provisioningProfiles: { 
          "com.tc.TodoApp" => "match AppStore com.tc.TodoApp",
        }
      }
    )
  end

  desc "upload to testflight"
  lane :upload do 
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "1510141436"
    )
  end

  desc "CD"
  lane :cd do
    ci
    fetch_signings
    archive
    upload
  end
end
